config/routes.rb
Rails.application.routes.draw do
  get '/menu', to: "static_pages#menu"
  get '/dashboard', to: "static_pages#dashboard"

  root "static_pages#home"

  resources :users do
    resources :orders
  end

  resources :categories

  resource :session
  resources :cart_items
end

app/models/cart.rb
class Cart
  attr_reader :data

  def initialize(cart_data)
    @data = cart_data || {}
  end

  def add_item(item_id)
    data[item_id] ||= 0
    data[item_id] += 1
  end 

  def total_count
    data.values.reduce(0, :+)
  end

  def total_cost
    data.map do |id, quantity|
      Item.find(id).price * quantity
    end.reduce(:+)
  end

  def decrease_quantity(item_id)
    data[item_id] -= 1
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :description, uniqueness: true, presence: true
  validates :price, presence: true

  belongs_to :category

  has_many :line_items
  has_many :orders, through: :line_items
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :item

  def name
    Item.find(item_id).name
  end

  def description
    Item.find(item_id).description
  end

  def price
    Item.find(item_id).price
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user

  has_many :line_items, :dependent => :destroy
  has_many :items, through: :line_items

  def create_line_items(cart_data)
    cart_data.map do |item_id, quantity|
      LineItem.create(item_id: item_id, quantity: quantity)
    end
  end

  def total_cost
    line_items.map do |line_item|
      line_item.price * line_item.quantity
    end.reduce(:+)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :load_cart

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def load_cart
    @cart ||= Cart.new(session[:cart])
  end

  def cart
    @cart
  end
  helper_method :cart

  def require_login
    unless current_user
      redirect_to new_session_path
      flash[:alert] = "Please log in first."
    end
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
    cart.add_item(params[:item_id]) 
    session[:cart] = cart.data
    item = Item.find(params[:item_id])
    flash[:notice] = "#{item.name.capitalize} added to cart."
    redirect_to menu_path
  end

  def index
  end

  def update
    if params[:modify] == "increase"
      cart.add_item(params[:id])
      redirect_to :back
    else
      if cart.data[params[:id]] == 1
        session[:cart].delete(params[:id])
        redirect_to :back
      else
        cart.decrease_quantity(params[:id])
        redirect_to :back
      end
    end
  end

  def destroy
    session[:cart].delete(params[:id])
    redirect_to :back
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new(category_params)
    if category.save
      flash[:notice] = "#{category.name} successfully created!"
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find_by(id: params[:id])
  end

  def update
    @category = Category.find_by(id: params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    category = Category.find_by(id: params[:id])
    category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_login
  before_action :authorize!

  def index
    @user = User.find(params[:user_id])
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    if current_user
      order = current_user.orders.create do |order|
        cart.data.each do |item_id, quantity|
          order.line_items.build do |line_item|
            line_item.item_id  = item_id
            line_item.quantity = quantity 
          end
        end
      end
      @order = order
      @order.save
      session[:cart].clear
      flash[:notice] = "Thank you for your order"
      redirect_to user_orders_path(params[:user_id])
    else
      redirect_to root_path
    end
  end

  private

  def authorize!
    unless current_user.id == params[:user_id].to_i
      flash[:alert] = "Unauthorized access!"
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    session[:previous_url] = request.referrer
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user and user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      if user.admin == true
        redirect_to dashboard_path
      else
        redirect_to session[:previous_url]
      end
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def menu
    @categories = Category.all
  end

  def dashboard
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]
  before_action :authorize!, only: [:show, :edit, :update, :index]
  
  def show
    @user = User.find(params[:id])
  end

  def new
    session[:before_register_url] = request.referrer
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to session[:before_register_url]
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to user_path(user.id)
    else
      render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def authorize!
    unless current_user.id == params[:id].to_i
      flash[:alert] = "Unauthorized access!"
      redirect_to root_path
    end 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def formatted_price(amount)
    number_to_currency(amount/100, precision: 2)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_login(user)
      visit root_path
      click_on "Login"
      fill_in "session[email]", with: user.email
      fill_in "session[password]", with: user.password
      click_on("Submit")
  end
end

app/views/cart_items/index.html.erb
<h1>Cart Page</h1>
<% if cart.total_count > 0 %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th></th>
      <th>Quantity</th>
      <th></th>
      <th>Sub-Total</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% cart.data.each do |id, quantity| %>
      <% item = Item.find(id) %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.description %></td>
      <td><%= formatted_price(item.price) %></td>
      <td class="increase-button"><%= button_to "+", cart_item_path(item.id, modify: "increase"), method: :put %>
      <td class="item-quantity"><%= quantity %></td>
      <td class="decrease-button"><%= button_to "-", cart_item_path(item.id, modify: "decrease"), method: :put %>
      <td><%= formatted_price(item.price * quantity) %></td>
      <td><%= button_to "Remove", cart_item_path(item.id), method: :delete %>
    </tr>
    <% end %>
  </tbody>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th>Total:</th>
    <th><%= formatted_price(cart.total_cost) %></th>
    <th></th>
  </tr>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <% if current_user %>
      <th><%= button_to "Place Order", user_orders_path(current_user.id), class: "btn btn-default place-order" %></th>
    <% else %>
      <th><%= link_to "Place Order", new_session_path, class: "btn btn-default place-order" %></th>
    <% end %>
  </tr>
</table>
<% else %>
  <div class="row">
    <div class="col-xs-4 col-xs-offset-4 empty-cart">
      <h1>Cart is empty</h1>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Update Category" %>
<% end %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= link_to "Create New Category", new_category_path %>


<table class="table">
  <thead>
    <tr>
      <th>Category Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to "Edit", edit_category_path(category) %></td>
        <td><%= link_to "Delete", category_path(category), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sheazonne's Restaurant</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Playball' rel='stylesheet' type='text/css'>
  <script type="text/javascript" src="script.js"></script>
</head>
<body>
  <%= render 'partials/header' %>
  
  <% flash.each do |name, msg| %>
   <%= content_tag :div, msg, class: "flash_#{name}" %>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/orders/index.html.erb
<h1>Order History Page</h1>

<table class="table">
  <thead>
    <tr>
      <th>Order</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @user.orders.reverse_each do |order| %>
      <tr>
        <td><%= link_to order.created_at, user_order_path(@user.id, order.id) %></td>
        <td><%= order.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/show.html.erb
<h1>Order #<%= @order.id %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Sub-Total</th>
    </tr>
  </thead>
  <tbody>
    <% @order.line_items.each do |line_item| %>
    <tr>
      <td><%= line_item.name %></td>
      <td><%= line_item.description %></td>
      <td><%= formatted_price(line_item.price) %></td>
      <td><%= line_item.quantity %></td>
      <td><%= formatted_price(line_item.price * line_item.quantity) %></td>
    </tr>
    <% end %>
  </tbody>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th>Total:</th>
    <th><%= formatted_price(@order.total_cost) %></th>
  </tr>
</table>

app/views/partials/_header.html.erb
<header>
  <div class="row">
    <div class="col-xs-8" id="restaurant-name">
      <h1>Sheazonne's Italian Restaurant</h1>
    </div>
    <div class="col-xs-4" id="login-register">
      <div style="float: right; padding-top: 30px; padding-right: 50px; font-size: 20px;">
        <% if current_user %>
          <span class="user-welcome">Welcome, <%= current_user.username.capitalize %>!</span>
          <span><%= link_to "Logout", session_path, method: :delete %></span>
        <% else %>
          <span><%= link_to "Login", new_session_path %></span> |
          <span><%= link_to "Register", new_user_path %></span>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-8">
      <div id="categories">
        <%= link_to "Home", root_path %> |
        <%= link_to "Menu", menu_path %>
        <% if current_user %>
          | <%= link_to "My Account", user_path(current_user.id) %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-4">
      <div id="cart">
        <%= link_to "Cart:", cart_items_path %> <%= cart.total_count %> items
      </div>
    </div>
  </div>
</header>
  

app/views/static_pages/dashboard.html.erb
<h1>Admin Dashboard</h1>

<%= link_to "Categories", categories_path %>

app/views/static_pages/home.html.erb
<div class="row home-background">
  <div class="col-xs-3">
    <div class="row quotes">
      "World's Best Pizza!"
    </div>
  </div>
  <div class="col-xs-4">
    <%= image_tag("pizza.jpg") %>
  </div>
  <div class="col-xs-5">
    <div class="row quotes">
      "Voted #1 Pizza 2015!"
    </div>
  </div>
</div>

app/views/static_pages/menu.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 category-links">
    <h3><a href="#appetizers">Appetizers</a> | <a href="#pasta">Pasta</a> | <a href="#pizza">Pizza</a> | <a href="#dessert">Dessert</a> | <a href="#beverages">Beverages</a></h3>
    <div class="row">
      <% @categories.each do |category| %>
        <div class="row category-block">
        <div class="row category-title">
          <h3 id="<%= category.name  %>"><%= category.name.capitalize %></h3>
        </div>
        <% category.items.each do |item| %>
        <div class="item">
          <div class="col-xs-2 item-name"><%= item.name.capitalize %></div>
          <div class="col-xs-6 item-description"><%= item.description[0..55] %></div>
          <div class="col-xs-2"><%= formatted_price(item.price) %></div>
          <div class="col-xs-2 add-to-cart"><%= button_to "Add to Cart", cart_items_path(item_id: item.id), id: "button_yes" %></div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 style="margin-left: 12px;">User Edit Account Page</h1>

<%= form_for @user do |f| %>
  <div class="col-xs-2">
    <%= f.label :username %>
  </div>
  <div class="row">
    <div class="col-xs-4 field-font">
      <%= f.text_field :username %>
    </div>
  </div>
  <div class="col-xs-2">
    <%= f.label :email %>
  </div>
  <div class="row">
    <div class="col-xs-4 field-font">
      <%= f.email_field :email %>
    </div>
  </div>
  <div class="col-xs-2 register-submit">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1 style="margin-left: 12px;">User Registration Page</h1>

<%= form_for @user do |f| %>
  <div class="col-xs-2">
    <%= f.label :username %>
  </div>
  <div class="row">
    <div class="col-xs-4 field-font">
      <%= f.text_field :username %>
    </div>
  </div>
  <div class="col-xs-2">
    <%= f.label :email %>
  </div>
  <div class="row">
    <div class="col-xs-4 field-font">
      <%= f.email_field :email %>
    </div>
  </div>
  <div class="col-xs-2">
    <%= f.label :password %>
  </div>
  <div class="row">
    <div class="col-xs-4 font-field">
      <%= f.password_field :password %>
    </div>
  </div>
  <div class="col-xs-2">
    <%= f.label :password_confirmation %>
  </div>
  <div class="row">
    <div class="col-xs-4 font-field">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>
  <div class="col-xs-2 register-submit">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Account Info Page</h1>

<p>
Name: <%= @user.username %>
</p>
<p>
  Email: <%= @user.email %>
</p>
<p>
  <%= button_to "Edit Account", edit_user_path(@user.id), method: :get %>
</p>
<p>
  <%= link_to "Order History", user_orders_path(@user.id) %>
</p>